### ISSUE TITLE
Give Karolis write access to the repo

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/tlapm#101]
This would reduce the bus factor, protect from burnout, and keep commits moving. I would be happy to start volunteering some time reviewing PRs here so there are another set of eyes on things. Thoughts? @kape1395

**Comment by kape1395** [comment]
Thanks for the support :)
The reviews and approvals from the core TLAPM developers would be needed anyway.
Nevertheless, more eyes on the code would be useful.

**Comment by muenchnerkindl** [comment]
I certainly won't object to volunteers!

**Comment by ahelwer** [comment]
@muenchnerkindl it seems like there is a lot of pending work that needs to be evaluated & merged, how do you think I could best help with that?

**Comment by damiendoligez** [comment]
For the record: we had a meeting today and decided to give Karolis maintainer access because he has made great contributions to TLAPS, so that he can more easily help move the project forward.
