### ISSUE TITLE
LSP: The TLAPM parser often does not provide an error position.

### ISSUE THREAD

**Issue by kape1395** [tlaplus/tlapm#106]
This is on PR #93.

The LSP server uses the TLAPM parser to derive the proof structure before handling separate obligations.
This parser often gives just a generic error (file cannot be parsed) and provides no line/position or error explanation.

Not sure how to approach this. Can this parser be improved, or should another approach be taken here?

**Comment by muenchnerkindl** [comment]
TLAPM was indeed developed assuming that the module is accepted by SANY (not just parsing, but also level checking). The Toolbox runs SANY whenever the module is saved, which is not the default setting for VSCode. We also (unsuccessfully) experimented with replacing the TLAPM parser by SANY.

**Comment by kape1395** [comment]
This commit improved error reporting a lot:
https://github.com/tlaplus/tlapm/pull/93/commits/5dc0169dbad41d630da131771a1f5816211567ee

**Comment by kape1395** [comment]
#93 is merged now, and error reporting has been improved there. Closing this issue.
