### ISSUE TITLE
Mark release 202210041448 as latest

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/tlapm#117]
This is a minor change but it would be nice to mark release [202210041448](https://github.com/tlaplus/tlapm/releases/tag/202210041448) as latest. The only reason for this is then various scripts can download it from https://github.com/tlaplus/tlapm/releases/latest instead of having to store and type out the version number. Good preparation for rolling releases.

**Comment by kape1395** [comment]
@muenchnerkindl, can we consider this release as the "best"? If yes, I can mark it as the latest.

**Comment by muenchnerkindl** [comment]
@kape1395 Sounds reasonable to me.
