### ISSUE TITLE
Why the standard modules can be overriden?

### ISSUE THREAD

**Issue by kape1395** [tlaplus/tlapm#118]
There is a proof:
```
---- MODULE testnat ----
EXTENDS Naturals
THEOREM test == 0 \in Nat
OBVIOUS
====
```
It is proven if no additional paths are given:
```
$ opam exec -- tlapm /home/karolis/CODE/pub/tlapm-lsp/deps/zenon/zenon-src/regression/backend/testnat.tla
...
[INFO]: All 1 obligation proved.
```

But after I added support for loading modules from jars/zips I found that this doesn't work:
```
$ opam exec -- tlapm /home/karolis/CODE/pub/tlapm-lsp/deps/zenon/zenon-src/regression/backend/testnat.tla \
  -I 'jar:/home/karolis/.vscode/extensions/alygin.vscode-tlaplus-nightly-2024.2.606/tools/tla2tools.jar!tla2sany/StandardModules'

(* created new ".tlacache/Naturals.tlaps/Naturals.thy" *)
(* fingerprints written in ".tlacache/Naturals.tlaps/fingerprints" *)
File "Naturals.tla", line 1, character 1 to line 36, character 77:
[INFO]: All 0 obligation proved.
(* loading fingerprints in ".tlacache/testnat.tlaps/fingerprints" *)
(* created new ".tlacache/testnat.tlaps/testnat.thy" *)
(* fingerprints written in ".tlacache/testnat.tlaps/fingerprints" *)
File "/home/karolis/CODE/pub/tlapm-lsp/deps/zenon/zenon-src/regression/backend/testnat.tla", line 6, characters 1-7:
[ERROR]: Could not prove or check:
           0 \in Nat
File "/home/karolis/CODE/pub/tlapm-lsp/deps/zenon/zenon-src/regression/backend/testnat.tla", line 1, character 1 to line 8, character 4:
[ERROR]: 1/1 obligation failed.
There were backend errors processing module `"testnat"`.
 tlapm ending abnormally with Failure("backend errors: there are unproved obligations")
Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
Called from Tlapm_lib.process_module in file "src/tlapm_lib.ml", line 446, characters 12-77
Called from Tlapm_lib.main.f in file "src/tlapm_lib.ml", line 573, characters 23-43
Called from Stdlib__List.fold_left in file "list.ml", line 123, characters 24-34
Called from Tlapm_lib.main in file "src/tlapm_lib.ml", line 576, characters 13-40
Called from Tlapm_lib.init in file "src/tlapm_lib.ml", line 588, characters 8-33
```

If I understand correctly, the standard/built-in module `Naturals` is now overridden by a module from the `tla2tools.jar`. This probably breaks some internal encodings for the backend provers.

@muenchnerkindl, maybe you know why there is a possibility of overriding the built-in modules? Is that intended, or a bug?

**Comment by muenchnerkindl** [comment]
I don't remember how built-in modules are recognized and what's the story with module overrides but @damiendoligez may know.

**Comment by kape1395** [comment]
There is even a test checking if the standard modules can be overridden. I understand why that could be useful for the TLC module, but overriding for Naturals and others looks strange.

https://github.com/tlaplus/tlapm/blob/b9b9a92b187b523cff0c70dfa3ab8d9cabf546dc/src/module/m_save.ml#L343

**Comment by kape1395** [comment]
I'll add an option for the `tlapm` to prefer StdLib instead of modules with the same name and will use it in the LSP server.  Probably `--prefer-stdlib`. The default behavior will remain the same.

**Comment by kape1395** [comment]
Option `--prefer-stdlib` is added in https://github.com/tlaplus/tlapm/pull/93.
