### ISSUE TITLE
Intermittent build failures in CI

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/tlapm#146]
Here are CI runs for the exact same change that produced different results:
1. [Every build succeeds except Ubuntu/OCaml 5.1.0](https://github.com/tlaplus/tlapm/actions/runs/10116608099)
2. [Every build succeeds except Ubuntu/OCaml 4.13.1](https://github.com/tlaplus/tlapm/actions/runs/10116794428)
3. [Every build succeeds except macOS/OCaml 5.1.0](https://github.com/tlaplus/tlapm/actions/runs/10117042432)
4. [Every build succeeds except macOS/OCaml 4.13.1](https://github.com/tlaplus/tlapm/actions/runs/10126228086)

The `make build` step nondeterministically fails. It's difficult to parse the log to determine why this is; in both cases you can find the line:
> make: *** [Makefile:27: build] Error 1
##[error]Process completed with exit code 2.

You can also find the line:
>make[1]: *** [Makefile:35: ../../_build_cache/Isabelle2011-1_bundle_x86-linux.tar.gz] Error 4

Other than that I can't tell why this is happening, but this should be a high priority issue because it's very hard to merge PRs until this is fixed.

**Comment by kape1395** [comment]
This is most likely due to randomly failing Isabelle's theory build. I haven't seen such failures with the newer Isabelle version, so I hope this will be solved after merging that PR.

**Comment by ahelwer** [comment]
One weird thing is that this only seems to happen for the license change branch. I have no idea why. Consistently only a single random runner fails while the others succeed. I've not yet seen other branches do this.

**Comment by ahelwer** [comment]
Turns out these failures were caused by me not adding the license field to `dune-project` in addition to `tlapm.opam`, and `tlapm.opam` is regenerated from `dune-project` every time `make` is run so the license field was just being removed from `tlapm.opam`. I don't know why having unstaged changes was failing the build but that's a mystery for another time.
