### ISSUE TITLE
Add instructions to debug tlapm

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlapm#2]
[https://asciinema.org/a/307459](https://asciinema.org/a/307459) and [https://www.youtube.com/watch?v=Eu46FmhpR_0&feature=youtu.be](https://www.youtube.com/watch?v=Eu46FmhpR_0&feature=youtu.be) are recordings of how to debug `tlapm` with `ocamldebug` and inside VSCode (on Linux).  Do you want me to add a section to INSTALL that references/mirrors the recordings?

**Comment by ahelwer** [comment]
I put a bunch of effort into trying to set this up a few months ago and was met with failure unfortunately: https://github.com/tlaplus/tlapm/discussions/143
