### ISSUE TITLE
tlapm problems

### ISSUE THREAD

**Issue by FilaliM** [tlaplus/tlapm#26]
I havre tried to launch tlapm with the --debug option.
(without the option the theorem colors green)
I get this messages:
Error running tlapm. Report a bug with the error code to the developers at https://github.com/tlaplus/tlapm/issues.
 
 Error code: 3
File "<unknown>"

File /usr/local/lib/tlaps/ not found
-----------
I have also tried to make and install from github 
After ./configure I get this message:
tourfan:tlapm filali$ make all install
tourfan:tlapm filali$ make
rm -f tlapm
/Library/Developer/CommandLineTools/usr/bin/make -C src tlapm.native
cd `dirname revision.mli` \
	&& ocamlc -annot -g -warn-error +1+2+5+6+8+10..26+29..31+36 -unsafe-string  -I . -I backend -I frontend -I expr -I module -I proof -I util -I pars -I typesystem -I smt -I ../backend -I ../frontend -I ../expr -I ../module -I ../proof -I ../util -I ../pars -I ../typesystem -I ../smt -I .. -c `basename revision.mli`
ocamlc: OCaml has been configured with -force-safe-string: -unsafe-string is not available.

(tourfan:tlapm filali$ ocaml --version
The OCaml toplevel, version 4.11.1)

Thanks

**Comment by lemmy** [comment]
You can grab a TLAPS installer for macOS and Linux built from the most recent commit at https://github.com/tlaplus/tlapm/releases.

**Comment by johnyf** [comment]
The `tlapm` option `--debug` requires an argument, for example `--debug tempfiles` will save the files that are generated to communicate with the backend solvers to the directory of auxiliary files (`./filename.tlaps/` or `./__tlacache__/filename.tlaps/` in branch `master` as of commit f827e371d0cdd03d36f3fbcc21096a16590069bf, or `./.tlacache/filename.tlaps/` after #20 is merged). Other values as arguments for the `--debug` option can be found by searching for `Params.debugging` in the source code, for example: https://github.com/tlaplus/tlapm/search?l=OCaml&q=Params.debugging&type=code .

The option `--verbose` (or `-v`) may also be useful.

Branch `master` at commit f827e371d0cdd03d36f3fbcc21096a16590069bf is compatible with OCaml version 4.08.1, but not OCaml version 4.11.1. #25 updates `tlapm` to OCaml version 4.11.0, please consider using the branch of that pull request, or equivalently the branch https://github.com/tlaplus/tlapm/tree/ci_ocaml_matrix .

**Comment by muenchnerkindl** [comment]
It seems to me that this issue doesn't require action at this point and can be closed.
