### ISSUE TITLE
Running TLAPM in a specification which extends Randomization results in a crash

### ISSUE THREAD

**Issue by uguryavuz** [tlaplus/tlapm#28]
I get the following TLAPM Warning when I attempt to run TLAPM on any theorem in a specification which extends `Randomization`, even if the said theorem does not use any definitions from the module.
```
File "/foo/bar/dir/TLA+/Specification.tla", line 2, characters 38-50
Unknown module "Randomization"
```

I get the following Problem Occurred prompt right afterwards:
```
'Prover Launch' has encountered a problem.
Error running tlapm. Report a bug with the error code to the developers at https://github.com/tlaplus/tlapm/issues.
 
 Error code: 3
```

Here is the corresponding line 2 of the specification:
`EXTENDS Integers, TLAPS, FiniteSets, Randomization`

Upon removing all references to `Randomization` and related expressions, TLAPM works as expected without raising any errors.

**Comment by lemmy** [comment]
`Randomization` is part of TLC.  You can simply copy&paste it into your spec directory.

Is the approach described in https://lamport.azurewebsites.net/tla/inductive-invariant.pdf the reason why `Randomization` appears in your spec?

**Comment by muenchnerkindl** [comment]
You may want to try using tlapm -I /path/to/Randomization.tla for extending the search path of tlapm. (From the Toolbox, use C-G C-P and enter the option at the bottom of the window.)

**Comment by uguryavuz** [comment]
@muenchnerkindl, that does not seem to solve the problem. In my macOS installation of the TLA+ Toolbox, `Randomization` seems to be in the `/Applications/TLA+ Toolbox.app/Contents/Eclipse/plugins/org.lamport.tlatools_1.0.0.202004251858/tla2sany/StandardModules/` directory along with the other standard modules. Adding this directory using `tlapm -I` yields the following error:

```
Oops, this seems to be a bug in TLAPM.
Please give feedback to developers.


 Failure("Module.Parser.parse_file")
Raised at file "stdlib.ml", line 29, characters 17-33
Called from file "m_save.ml", line 168, characters 28-50
Called from file "set.ml", line 381, characters 34-55
Called from file "set.ml", line 381, characters 39-54
Called from file "m_save.ml", line 149, characters 20-1023
Called from file "m_save.ml", line 27, characters 16-20
Called from file "tlapm.ml", line 328, characters 14-65
Called from file "tlapm.ml", line 348, characters 8-33

version == "1.4.5 (build 33809)"
built_with == "OCaml 4.09.0"
tlapm_executable == "/usr/local/bin/tlapm"
max_threads == 4
library_path == "/usr/local/lib/tlaps"
search_path == << "/Applications/TLA+ Toolbox.app/Contents/Eclipse/plugins/org.lamport.tlatools_1.0.0.202004251858/tla2sany/StandardModules/"
                , "/usr/local/lib/tlaps/" >>
zenon == "PATH='/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/lib/tlaps/bin'; zenon -p0 -x tla -oisar -max-time 1d \"$file\""
zenon version == "zenon version 0.8.4 [a268] 2017-11-14"
flatten_obligations == TRUE
normalize == TRUE
```

And these two warnings upon closing the error window:
```
File "/Applications/TLA+ Toolbox.app/Contents/Eclipse/plugins/org.lamport.tlatools_1.0.0.202004251858/tla2sany/StandardModules/Randomization.tla", line 48, character 31
Unexpected EOF
```
```
File "/Applications/TLA+ Toolbox.app/Contents/Eclipse/plugins/org.lamport.tlatools_1.0.0.202004251858/tla2sany/StandardModules/Randomization.tla", line 49, character 1
Unexpected TAB character. TLAPS does not handle TAB characters in source files.
```

@lemmy, That is correct -- I am attempting to verify an inductive invariant for a large model and I saw the `Randomization` approach in that document. Your suggestion seems to work, as I have been able to run TLAPM without any issues once I copied `Randomization.tla` into my spec directory. But I'm still curious as to why this error happens, given that it doesn't happen with any of the other standard modules.

**Comment by lemmy** [comment]
@uguryavuz Consider moving the `Randomization`-related definitions out of your spec into a dedicated `MC.tla` module that is used for model-checking.

**Comment by johnyf** [comment]
The second error reported above (https://github.com/tlaplus/tlapm/issues/28#issuecomment-766099236) was caused due to `tlapm` not parsing tab characters. It has been addressed by a change to the module `Randomization` in commit https://github.com/tlaplus/tlaplus/commit/6ed7d29a47ec25fe8c96d86a7e55b62112f3a2cf.
