### ISSUE TITLE
CodeOfConduct

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlapm#37]
As discussed elsewhere, please consider adding a Code of Conduct.  The sibling repository adopted: https://github.com/tlaplus/tlaplus/blob/master/.github/CODE_OF_CONDUCT.md

**Comment by johnyf** [comment]
I support adding a code of conduct. Thank you for suggesting it.

**Comment by johnyf** [comment]
Addressed in commit 77cd0c0b09dc373745816d22c7617fc01d591c93.
