### ISSUE TITLE
Easy way to set up portable TLAPS?

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/tlapm#72]
I'd like to run TLAPS in a continuous integration workflow to check proofs on a variety of specs. Is there a way to easily download a portable version of TLAPS where all executables and dependencies can be contained to a specific directory?

**Comment by lemmy** [comment]
On Linux (and macOS?), the following works.  The caching only exists to be less affected by outages of the INRIA machine:

https://github.com/lemmy/BlockingQueue/blob/14a1baed2dd80ce83f32687c67749b39320ea121/.github/workflows/main.yml#L20-L29
