### ISSUE TITLE
Fingerprints seemingly ignored for some proofs

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/tlapm#85]
Using the [202210041448](https://github.com/tlaplus/tlapm/releases/tag/202210041448) release, the following proofs in the tlaplus/examples repo take a long time to check regardless of whether they were previously checked and their fingerprints stored in the .tlacache directory:

```
specifications/LoopInvariance/Quicksort.tla
specifications/LoopInvariance/SumSequence.tla
specifications/bcastByz/bcastByz.tla
```
This proof only takes six seconds to check but it still takes six seconds to check even if its fingerprints exist:
```
specifications/MisraReachability/ReachabilityProofs.tla
```
To help with differentiation, checking the following proofs is correctly greatly sped up when their fingerprints exist, going from ~10 seconds to ~0.5 seconds:
```
specifications/LoopInvariance/BinarySearch.tla
specifications/MisraReachability/ReachableProofs.tla
specifications/TeachingConcurrency/SimpleRegular.tla
```

**Comment by lemmy** [comment]
Possibly related https://github.com/tlaplus/tlapm/pull/84

**Comment by ahelwer** [comment]
Wow weird coincidence, I had been sitting on this issue for months!

**Comment by ahelwer** [comment]
Oops reopening because the PR isn't yet merged I guess

**Comment by kape1395** [comment]
#84 is merged now. Can we close this issue?

**Comment by ahelwer** [comment]
Probably!
