### ISSUE TITLE
Introduce a `develop` branch?

### ISSUE THREAD

**Issue by kape1395** [tlaplus/tlapm#92]
Maybe it would be easier to integrate different changes if TLAPM had a `develop` branch along with the `master` (or `main`)?

In such a case, all the pull requests should be based on the `develop` branch and be merged first back to it. While the main branch is expected to be stable, the `develop` could have all the ongoing changes integrated and tested together. When the code quality in the `develop` branch is deemed ready for a release, it could be merged into the `master`, and a release would be produced based on it.

**Comment by muenchnerkindl** [comment]
Sounds like a good suggestion to me!

**Comment by kape1395** [comment]
Do you know how we can proceed with that? Probably that's:
 - The team has to decide on that. Or is the decision already made?
  - Someone from the maintainers should create the `develop` branch based on the `main` branch.
      - That should be a protected branch on Git Hub (commits can only be done via PRs to that branch).
      - If we encourage users to experiment with the development version, that branch could be made a default one. This is optional.
  - I would rebase my PRs to the `develop`.
  - Then, the approved PRs could be merged into that branch.

**Comment by ahelwer** [comment]
Personal opinion, I think it would be better to keep main as the development branch. Upload the build of main to the Inria nightly build server, same as the TLA+ tools. Keep the commits flowing into main and don't worry too too much about the odd bug, use releases to mark the state of the branch as stable. See PR #96

**Comment by ahelwer** [comment]
One obstacle to rolling releases is that the current head of the main branch does not do well on the tlaplus/examples corpus: https://github.com/tlaplus/tlapm/actions/runs/6680011626/job/18152686044

**Comment by ahelwer** [comment]
@kape @lemmy could I be added as an owner of this repo to make it easier to deal with releases, CI secrets, etc.? Alternatively see if you can create a role that lets me manage those things without all the other privileges if you want.

**Comment by lemmy** [comment]
Paging @damiendoligez and @muenchnerkindl.

**Comment by muenchnerkindl** [comment]
I have no objection.

**Comment by ahelwer** [comment]
Okay who has the permissions to make this change?

**Comment by lemmy** [comment]
"ahelwer has been added as a collaborator with maintain permissions on the repository."

**Comment by ahelwer** [comment]
This does give me the ability to draft new releases but I don't have access to CI settings. The "Code and automation" setting panel.

**Comment by kape1395** [comment]
This is not relevant anymore. Let's use the main branch.
